### ISSUE TITLE
No longer works on OpenATV

### ISSUE THREAD

**Issue by ian10951** [Dima73/enigma2-plugin-extensions-historyzapselector#6]
No module named Screens.Serviceinfo

For now I've just commented it out in the historyzap.py to get it to work again, obviously atv have changed this file in a recent update. Probably IanSav refactoring again for a change.

**Comment by Dima73** [comment]
[Fix module ServiceInfo](https://github.com/Dima73/enigma2-plugin-extensions-historyzapselector/commit/5748ccb3a7054b3722f6b0ce5df8b0b39c4fe6e8)
